/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author NHAT TUNG
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnQuenMatKhau = new javax.swing.JButton();
        btnGUIQuanLy = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtPassWord = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 450));
        getContentPane().setLayout(null);

        jLabel1.setText("Tên đăng nhập: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 160, 90, 28);

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUserName);
        txtUserName.setBounds(500, 160, 190, 29);

        jLabel3.setText("Mật khẩu:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 210, 70, 15);

        btnQuenMatKhau.setBackground(new java.awt.Color(153, 153, 255));
        btnQuenMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        btnQuenMatKhau.setText("Quên mật khẩu?");
        getContentPane().add(btnQuenMatKhau);
        btnQuenMatKhau.setBounds(560, 250, 130, 25);

        btnGUIQuanLy.setBackground(new java.awt.Color(153, 153, 255));
        btnGUIQuanLy.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnGUIQuanLy.setForeground(new java.awt.Color(255, 255, 255));
        btnGUIQuanLy.setText("Đăng nhập");
        btnGUIQuanLy.setBorder(null);
        btnGUIQuanLy.setPreferredSize(new java.awt.Dimension(100, 25));
        getContentPane().add(btnGUIQuanLy);
        btnGUIQuanLy.setBounds(440, 300, 160, 44);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Đăng nhập");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(490, 110, 61, 16);
        getContentPane().add(txtPassWord);
        txtPassWord.setBounds(500, 200, 190, 29);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgLogin2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 740, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGUIQuanLy;
    private javax.swing.JButton btnQuenMatKhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtPassWord;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
