/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author NHAT TUNG
 */
public class frmXuLyBanHang extends javax.swing.JPanel {

    /**
     * Creates new form frmXuLyBanHang
     */
    public frmXuLyBanHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnSanPham = new javax.swing.JPanel();
        txtMaSP = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        btnLamMoiSP = new javax.swing.JButton();
        spSanPham = new javax.swing.JScrollPane();
        tbSanPham = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnHoaDon = new javax.swing.JPanel();
        lbThongTinHD = new java.awt.Label();
        lbMaHD = new javax.swing.JLabel();
        lbSDT = new javax.swing.JLabel();
        lbTenKH = new javax.swing.JLabel();
        lbNgayLap = new javax.swing.JLabel();
        btnTim = new javax.swing.JButton();
        btnXoaSP = new javax.swing.JButton();
        spSPHD = new javax.swing.JScrollPane();
        tbSpHD = new javax.swing.JTable();
        txtSDT = new java.awt.TextField();
        lbTienNhan = new javax.swing.JLabel();
        lbTongTien = new javax.swing.JLabel();
        lbTongCong = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JLabel();
        lbKhuyenMai = new javax.swing.JLabel();
        lbTienDuaLai = new javax.swing.JLabel();
        txtKhuyenMai = new javax.swing.JLabel();
        txtTienDuaLai = new javax.swing.JLabel();
        txtTongCong = new javax.swing.JLabel();
        txtTienNhan = new java.awt.TextField();
        txtMaHD = new javax.swing.JLabel();
        txtNgayLap = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnLamMoiHD = new javax.swing.JButton();
        btnHangDoi = new javax.swing.JButton();
        btnDsHD = new javax.swing.JButton();
        cbInHD = new javax.swing.JCheckBox();
        btnThanhToan = new javax.swing.JButton();
        spThem = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1400, 680));

        pnSanPham.setBorder(javax.swing.BorderFactory.createTitledBorder("Sản phẩm"));

        txtMaSP.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtTenSP.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnLamMoiSP.setBackground(new java.awt.Color(153, 153, 255));
        btnLamMoiSP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLamMoiSP.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoiSP.setText("Làm Mới");
        btnLamMoiSP.setBorder(new javax.swing.border.MatteBorder(null));

        spSanPham.setViewportView(null);

        tbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Màu sắc", "Size", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSanPham.setRowHeight(35);
        tbSanPham.getTableHeader().setReorderingAllowed(false);
        spSanPham.setViewportView(tbSanPham);
        if (tbSanPham.getColumnModel().getColumnCount() > 0) {
            tbSanPham.getColumnModel().getColumn(2).setMaxWidth(80);
            tbSanPham.getColumnModel().getColumn(3).setMaxWidth(50);
            tbSanPham.getColumnModel().getColumn(4).setMaxWidth(80);
        }

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel1.setText("Mã sản phẩm");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel2.setText("Tên sản phẩm");

        javax.swing.GroupLayout pnSanPhamLayout = new javax.swing.GroupLayout(pnSanPham);
        pnSanPham.setLayout(pnSanPhamLayout);
        pnSanPhamLayout.setHorizontalGroup(
            pnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSanPhamLayout.createSequentialGroup()
                .addGroup(pnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnSanPhamLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(pnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnSanPhamLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLamMoiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnSanPhamLayout.setVerticalGroup(
            pnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSanPhamLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLamMoiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin hóa đơn"));

        lbThongTinHD.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lbThongTinHD.setName(""); // NOI18N
        lbThongTinHD.setText("Hóa đơn bán lẻ");

        lbMaHD.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbMaHD.setText("Mã hóa đơn");

        lbSDT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbSDT.setText("Số điện thoại");
        lbSDT.setToolTipText("");

        lbTenKH.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbTenKH.setText("Tên khách hàng");

        lbNgayLap.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbNgayLap.setText("Ngày lập");

        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_search_26px_3.png"))); // NOI18N
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnXoaSP.setBackground(new java.awt.Color(153, 153, 255));
        btnXoaSP.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnXoaSP.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaSP.setText("Xóa SP");
        btnXoaSP.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tbSpHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Sản phẩm", "Màu sắc", "Size", "Đơn giá", "Số lượng", "Thành tiền", "Giảm giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSpHD.setRowHeight(30);
        tbSpHD.getTableHeader().setReorderingAllowed(false);
        spSPHD.setViewportView(tbSpHD);
        if (tbSpHD.getColumnModel().getColumnCount() > 0) {
            tbSpHD.getColumnModel().getColumn(1).setMaxWidth(80);
            tbSpHD.getColumnModel().getColumn(2).setMaxWidth(50);
            tbSpHD.getColumnModel().getColumn(3).setMinWidth(90);
            tbSpHD.getColumnModel().getColumn(3).setMaxWidth(90);
            tbSpHD.getColumnModel().getColumn(4).setMaxWidth(80);
            tbSpHD.getColumnModel().getColumn(5).setMinWidth(90);
            tbSpHD.getColumnModel().getColumn(5).setMaxWidth(90);
            tbSpHD.getColumnModel().getColumn(6).setMinWidth(90);
            tbSpHD.getColumnModel().getColumn(6).setMaxWidth(90);
        }

        txtSDT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        lbTienNhan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbTienNhan.setText("Tiền nhận");

        lbTongTien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbTongTien.setText("Tổng tiền");

        lbTongCong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbTongCong.setText("Tổng cộng (thuế)");

        txtTongTien.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtTongTien.setForeground(new java.awt.Color(255, 0, 0));
        txtTongTien.setText("0.000 VNĐ");
        txtTongTien.setToolTipText("");

        lbKhuyenMai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbKhuyenMai.setText("Khuyến mãi");

        lbTienDuaLai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbTienDuaLai.setText("Tiền đưa lại");

        txtKhuyenMai.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtKhuyenMai.setForeground(new java.awt.Color(102, 102, 102));
        txtKhuyenMai.setText("0.000 VNĐ");
        txtKhuyenMai.setToolTipText("");

        txtTienDuaLai.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtTienDuaLai.setForeground(new java.awt.Color(255, 0, 0));
        txtTienDuaLai.setText("0.000 VNĐ");
        txtTienDuaLai.setToolTipText("");

        txtTongCong.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtTongCong.setForeground(new java.awt.Color(255, 0, 0));
        txtTongCong.setText("0.000 VNĐ");
        txtTongCong.setToolTipText("");

        txtTienNhan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTienNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienNhanActionPerformed(evt);
            }
        });

        txtMaHD.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtMaHD.setForeground(new java.awt.Color(255, 0, 0));
        txtMaHD.setText("HD00001");
        txtMaHD.setToolTipText("");

        txtNgayLap.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtNgayLap.setForeground(new java.awt.Color(255, 0, 0));
        txtNgayLap.setText("1/1/2023");
        txtNgayLap.setToolTipText("");

        txtTenKH.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTenKH.setText("Tên khách hàng");

        javax.swing.GroupLayout pnHoaDonLayout = new javax.swing.GroupLayout(pnHoaDon);
        pnHoaDon.setLayout(pnHoaDonLayout);
        pnHoaDonLayout.setHorizontalGroup(
            pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spSPHD)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHoaDonLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbThongTinHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(241, 241, 241))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHoaDonLayout.createSequentialGroup()
                        .addGroup(pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMaHD)
                            .addComponent(lbNgayLap))
                        .addGap(18, 18, 18)
                        .addGroup(pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaHD)
                            .addComponent(txtNgayLap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addGroup(pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTenKH)
                            .addComponent(lbSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnHoaDonLayout.createSequentialGroup()
                                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTenKH))
                        .addGap(3, 12, Short.MAX_VALUE)
                        .addComponent(btnXoaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnHoaDonLayout.createSequentialGroup()
                        .addGroup(pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTongTien)
                            .addComponent(lbTongCong)
                            .addComponent(lbTienNhan))
                        .addGap(24, 24, 24)
                        .addGroup(pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnHoaDonLayout.createSequentialGroup()
                                .addComponent(txtTienNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbTienDuaLai, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTongTien)
                            .addGroup(pnHoaDonLayout.createSequentialGroup()
                                .addComponent(txtTongCong)
                                .addGap(121, 121, 121)
                                .addComponent(lbKhuyenMai)))
                        .addGap(18, 18, 18)
                        .addGroup(pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKhuyenMai)
                            .addComponent(txtTienDuaLai))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnHoaDonLayout.setVerticalGroup(
            pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHoaDonLayout.createSequentialGroup()
                .addComponent(lbThongTinHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnHoaDonLayout.createSequentialGroup()
                        .addGroup(pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaHD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNgayLap)
                            .addComponent(txtNgayLap)))
                    .addGroup(pnHoaDonLayout.createSequentialGroup()
                        .addGroup(pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbSDT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnHoaDonLayout.createSequentialGroup()
                                .addGroup(pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnHoaDonLayout.createSequentialGroup()
                                        .addGap(0, 1, Short.MAX_VALUE)
                                        .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)))
                        .addGap(4, 4, 4)
                        .addGroup(pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTenKH)
                            .addComponent(txtTenKH))))
                .addGap(11, 11, 11)
                .addComponent(btnXoaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spSPHD, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTongTien)
                    .addComponent(txtTongTien))
                .addGap(18, 18, 18)
                .addGroup(pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTongCong)
                    .addComponent(lbKhuyenMai)
                    .addComponent(txtKhuyenMai)
                    .addComponent(txtTongCong))
                .addGap(18, 18, 18)
                .addGroup(pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbTienNhan)
                        .addComponent(lbTienDuaLai)
                        .addComponent(txtTienDuaLai))
                    .addComponent(txtTienNhan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnThem.setBackground(new java.awt.Color(153, 153, 255));
        btnThem.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText(">>");

        btnLamMoiHD.setBackground(new java.awt.Color(153, 153, 255));
        btnLamMoiHD.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnLamMoiHD.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoiHD.setText("Làm mới hóa đơn");
        btnLamMoiHD.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLamMoiHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiHDActionPerformed(evt);
            }
        });

        btnHangDoi.setBackground(new java.awt.Color(153, 153, 255));
        btnHangDoi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnHangDoi.setForeground(new java.awt.Color(255, 255, 255));
        btnHangDoi.setText("Thêm vào hàng đợi");
        btnHangDoi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnDsHD.setBackground(new java.awt.Color(153, 153, 255));
        btnDsHD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnDsHD.setForeground(new java.awt.Color(255, 255, 255));
        btnDsHD.setText("Danh sách hàng đợi");
        btnDsHD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDsHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDsHDActionPerformed(evt);
            }
        });

        cbInHD.setSelected(true);
        cbInHD.setText("In hóa đơn");
        cbInHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbInHDActionPerformed(evt);
            }
        });

        btnThanhToan.setBackground(new java.awt.Color(153, 153, 255));
        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToan.setText("Thanh Toán");
        btnThanhToan.setBorder(new javax.swing.border.MatteBorder(null));
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        int maxSP = 10;
        spThem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        spThem.setModel(new javax.swing.SpinnerNumberModel(1, 1, maxSP, 1));
        spThem.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spThemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel3.setText("LẬP HÓA ĐƠN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spThem, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnHangDoi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDsHD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbInHD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLamMoiHD, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamMoiHD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(296, 296, 296)
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spThem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbInHD, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDsHD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHangDoi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pnSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimActionPerformed

    private void txtTienNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienNhanActionPerformed

    private void btnDsHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDsHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDsHDActionPerformed

    private void cbInHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbInHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbInHDActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void spThemStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spThemStateChanged

    }//GEN-LAST:event_spThemStateChanged

    private void btnLamMoiHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLamMoiHDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDsHD;
    private javax.swing.JButton btnHangDoi;
    private javax.swing.JButton btnLamMoiHD;
    private javax.swing.JButton btnLamMoiSP;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoaSP;
    private javax.swing.JCheckBox cbInHD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbKhuyenMai;
    private javax.swing.JLabel lbMaHD;
    private javax.swing.JLabel lbNgayLap;
    private javax.swing.JLabel lbSDT;
    private javax.swing.JLabel lbTenKH;
    private java.awt.Label lbThongTinHD;
    private javax.swing.JLabel lbTienDuaLai;
    private javax.swing.JLabel lbTienNhan;
    private javax.swing.JLabel lbTongCong;
    private javax.swing.JLabel lbTongTien;
    private javax.swing.JPanel pnHoaDon;
    private javax.swing.JPanel pnSanPham;
    private javax.swing.JScrollPane spSPHD;
    private javax.swing.JScrollPane spSanPham;
    private javax.swing.JSpinner spThem;
    private javax.swing.JTable tbSanPham;
    private javax.swing.JTable tbSpHD;
    private javax.swing.JLabel txtKhuyenMai;
    private javax.swing.JLabel txtMaHD;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JLabel txtNgayLap;
    private java.awt.TextField txtSDT;
    private javax.swing.JLabel txtTenKH;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JLabel txtTienDuaLai;
    private java.awt.TextField txtTienNhan;
    private javax.swing.JLabel txtTongCong;
    private javax.swing.JLabel txtTongTien;
    // End of variables declaration//GEN-END:variables
}
